<?xml version="1.0" encoding="UTF-8" ?>
<definitions name="fet.dummyServer.mdm" targetNamespace="fet.dummyServer.mdm"
	xmlns:tns="fet.dummyServer.mdm"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:fet.services.mdm="fet.services.mdm">

	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="fet.services.mdm" schemaLocation="fet.services.mdm.xsd"/>
		</schema>
	</types>

	<message name="UpdateTxRequest">
		<part name="UpdateTxRequest" type="fet.services.mdm:UpdateTxRequest"/>
	</message>

	<message name="UpdateTxResponse">
		<part name="UpdateTxResponse" type="fet.services.mdm:UpdateTxResponse"/>
	</message>

	<portType name="MDMInterface">
		<operation name="UpdateTx">
			<input message="tns:UpdateTxRequest"/>
			<output message="tns:UpdateTxResponse"/>
		</operation>
	</portType>

	<binding name="MDMBinding" type="tns:MDMInterface">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="UpdateTx">
			<soap:operation soapAction="UpdateTx"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>

	<service name="MDMExternalService">
		<port name="MDMPort" binding="tns:MDMBinding">
		</port>
	</service>

</definitions>